name: maids
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

