name: maids
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  # add injectable to your dependencies
  injectable:
  get_it:
  json_annotation: ^4.9.0
  isar: ^3.1.0+1
#  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
#  json_serializable: ^6.8.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  go_router: ^14.1.2
  animations: ^2.0.11
  internet_connection_checker_plus: ^2.3.0
  dio: ^5.4.3+1
  intl:
  intl_utils: ^2.6.1
  pretty_dio_logger: ^1.3.1
  google_fonts: ^6.2.1
  flex_color_scheme: ^7.3.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^4.2.1
  devicelocale: ^0.7.1
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.6.1
  another_flushbar: ^1.12.29
  fluttertoast: ^8.1.0
  animate_do: ^3.3.4
  flutter_staggered_animations: ^1.1.1
  path_provider: ^2.1.3
  flutter_adaptive_scaffold: ^0.1.10+2
  uuid: ^4.4.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  rxdart: ^0.27.7
  simple_animations: ^5.0.0
  supercharged: ^2.1.1
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  analyzer: ^5.13.0
#  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  isar_generator: 3.1.0+1
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

  build_runner: ^2.1.0
  json_serializable: ^6.1.0

  test: ^1.17.12
  mockito: ^5.1.0





flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/


flutter_intl:
  main_local: en
  enabled: true
  class_name: Translations
  arb_dir: lib/core/managers/localization/res
  output_dir: lib/core/managers/localization/generated

flutter_gen:
  output: lib/core/generated_files/assets/

  line_length: 80
  null_safety: true
  style: snake-case
  integrations:
    flutter_svg: true
    flare_flutter: true
  assets:
    enabled: true
  fonts:
    enabled: false

flutter_icons:
  image_path: "assets/images/app_launcher.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_launcher.png"
    background_color: "#6578FC"
    theme_color: "#6578FC"
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  # flutter pub run flutter_native_splash:remove
  # flutter pub run flutter_native_splash:create
  color: "#ffffff"
  image: assets/images/splash_logo.png
  color_dark: "#402aff"
  image_dark: assets/images/splash_logo.png
  android: true
  ios: true

  android_12:

